---
  - file: path=/etc/kubernetes/pki/etcd state=directory
  - copy: src={{role_path}}/files/pki/{{item}} dest=/etc/kubernetes/pki/etcd/{{item}}
    with_items:
    - "ca.crt"
    - "ca.key"
  - copy: src={{role_path}}/files/pki/{{item}} dest=/etc/kubernetes/pki/{{item}}
    with_items:
    - "ca.crt"
    - "ca.key"
  - copy: src={{role_path}}/files/etcd/{{item}} dest=/usr/local/bin/{{item}} mode=0755
    with_items:
    - "etcd"
    - "etcdctl"
